### ISSUE TITLE
49: 错误: 找不到符号             new AssetsLoadPackage()

### ISSUE THREAD

**Issue by zhilianghuang** [songxiaoliang/react-native-code-push-assets#2]
在 MainApplication.java: 会提示以下的问题
 错误: 找不到符号
            new AssetsLoadPackage()

符号: 类 AssetsLoadPackage

1 个错误

**Comment by songxiaoliang** [comment]
@zhilianghuang 检查下有没有import

**Comment by zhilianghuang** [comment]
谢谢，@songxiaoliang  我放到同级目录，按理来说不需要导入，等下我再使用import试试会不会有问题

**Comment by zhilianghuang** [comment]
@songxiaoliang 能提供下你的import嘛？android中的java代码不太懂,只会使用，谢了
